apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"
  use-proxy-protocol: "false"
  enable-real-ip: "true"
  proxy-real-ip-cidr: "0.0.0.0/0"

  # Logs
  log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id $host'

  # Server tokens
  server-tokens: "false"

  # Body size
  proxy-body-size: "100m"

  # Timeouts
  proxy-connect-timeout: "75"
  proxy-send-timeout: "75"
  proxy-read-timeout: "75"

  # SSL
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
  ssl-prefer-server-ciphers: "true"

  # Performance
  worker-processes: "auto"
  max-worker-connections: "16384"
  max-worker-open-files: "0"

  # Keep alive
  upstream-keepalive-connections: "320"
  upstream-keepalive-timeout: "60"
  upstream-keepalive-requests: "10000"
  keep-alive: "75"
  keep-alive-requests: "1000"

  # Buffers
  client-header-buffer-size: "1k"
  large-client-header-buffers: "4 8k"
  client-body-buffer-size: "8k"

  # Habilitar snippets
  allow-snippet-annotations: "true"

