apiVersion: v1
kind: Secret
metadata:
  name: fishing-map-secrets
  namespace: fishing-map
  labels:
    app: fishing-map
type: Opaque
stringData:
  DB_HOST: "__DB_HOST__"
  DB_PORT: "__DB_PORT__"
  DB_NAME: "__DB_NAME__"
  DB_USER: "__DB_USER__"
  DB_PASSWORD: "__DB_PASSWORD__"

  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "__REDIS_PASSWORD__"

  JWT_SECRET: "__JWT_SECRET__"

  API_KEY_WEATHER: "__API_KEY_WEATHER__"

  SPACES_ACCESS_KEY: "__SPACES_ACCESS_KEY__"
  SPACES_SECRET_KEY: "__SPACES_SECRET_KEY__"

---

apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: fishing-map
  labels:
    app: fishing-map
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7InVzZXJuYW1lIjoidG9rZW4iLCJwYXNzd29yZCI6InRva2VuIiwiYXV0aCI6ImRHOXJaVzQ2ZEc5clpXND0ifX19
